---
title: "Check Markers"
author: "AGC, AY"
date: "17 3 2021"
output: html_document
---

```{r setup, include=FALSE}

home = getwd()
output= paste0(home, "/output/")

source(paste0(home,"/code/custom_functions.R"))

library(DESeq2)
library(knitr)
library(tidyverse)
library(pheatmap)

opts_chunk$set(echo = TRUE, 
               fig.height = 7, 
               fig.width = 9, 
               message = TRUE,
               warning = TRUE,
               fig.align='center',
               dpi=500
)



```

```{r load_data}

load(paste0(output,"/dds_matrix.RData"))


```


```{r plotGOIS, fig.height=15, fig.width=10}

SampleInfo = as.data.frame(colData(ddsMat))
genedata=rowData(ddsMat)

SampleInfo = SampleInfo %>% dplyr::arrange(CellLine, desc(gRNA), desc(DIFF), desc(RAPA))

# image(SampleInfo %>% select( CellLine, gRNA, DIFF, RAPA) %>% mutate_all(as.numeric) %>% as.matrix)

GOIsEntrez=c(DEPDC5="9681",
             KI67="4288",
             CDC2="983",
             Tubb3="10381",
             Gfap="2670",
             VGLUT1 ="57030",
             VGLUT2="57084", 
             VGAT="140679", 
             GPHN="10243",
             S100B="6285",
             Nestin="10763",
             Synaptophysin="6855",
             GLast="6507",
             MTOR="2475",
             Olig2="10215",
             Aqp4="361",
             Akt="207",
             FGFR1="2260",
             FGFR2="2263",
             FGFR3="2261",
             FGFR4="2264",
             FGF1="2246",
             FGF2="2247",
             sox9="6662",
             TH="7054",
             Pax6="5080",
             SOX2="6657",
             EGFR="1956",
             EGF="1950",
             TSC1="7248",
             TSC2="7249",
             RPS6="6194",
             RPTOR="57521",
             NPRL2="10641",
             NPRL3="8131",
             DCX="1641",
             MAP2="4133",
             Ncam1="4684",
             Cx3cr1="1524",
             Gap_43="2596",
             Bassoon="8927",
             Psd95="1742",
             MSI1="4440",
             Neun="146713",
             Sox1="6656",
             Hes5="388585",
             GLUL="2752",
             Stx1a="6804",
             Stxbp1="6812",
             Homer1="9456",
             Mash1="429")



CellID = c("ReN")
exprobj=ddsMat


geneheatmap=function(GOIsEntrez,exprobj,CellID){
  
  idx = match(GOIsEntrez, rownames(exprobj))
  log_2cpm=log2(counts(exprobj, normalize=T)+1)
  idxsmpl = SampleInfo$CellLine %in% CellID
  
  dataset= log_2cpm[idx, rownames(SampleInfo)[idxsmpl]]
  
  colnames(dataset)= SampleInfo[rownames(SampleInfo)[idxsmpl],"label_rep"]
  rownames(dataset) = names(GOIsEntrez)
  
  #colors for plotting heatmap
  colors <- colorRampPalette( rev(brewer.pal(9, "Blues")) )(255)
  
  
  gRNAcol = Dark8[c(1:nlevels(SampleInfo$gRNA))+nlevels(SampleInfo$CellLine)]
  names(gRNAcol) = levels(SampleInfo$gRNA)
  
  diffcol = brewer.pal(3,"Set1")[1:nlevels(SampleInfo$DIFF)]
  names(diffcol) = levels(SampleInfo$DIFF)
  
  rapacol = brewer.pal(3,"Set2")[1:nlevels(SampleInfo$RAPA)]
  names(rapacol) = levels(SampleInfo$RAPA)
  
  ann_colors = list(
    DIFF = diffcol, 
    RAPA = rapacol,
    gRNA = gRNAcol)
  
  
  
  labels = SampleInfo[match(colnames(dataset), SampleInfo$label_rep),
                      c("gRNA","DIFF", "RAPA")] %>%  
    mutate_all(as.character) %>% as.data.frame()
  
  
  rownames(labels)=colnames(dataset)
  
  pheatmap(dataset, 
           cluster_rows = F,
           cluster_cols = F,
           scale = "row", 
           annotation_col = labels,
           annotation_colors = ann_colors, 
           main=CellID)
}

geneheatmap(GOIsEntrez,ddsMat,CellID="D62")
geneheatmap(GOIsEntrez,ddsMat,CellID="D244")
geneheatmap(GOIsEntrez,ddsMat,CellID="ReN")

```








